### ISSUE TITLE
[Metadata Store] [request]: Add labels to experiments

### ISSUE THREAD

**Issue by volkangurel** [layerai/roadmap#22]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I'd like to be able to add labels to my experiments (dataset builds and model trains) and use them to filter experiments in the "Analysis" view. I'd also like to be able to change labels on experiments in the Web UI.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

If I have too many experiments, it may be hard to find the exact ones I'm looking for. Filtering by labels would help me keep things more organized.

**Are you currently working around this issue?**

No workaround

**Additional context**

N/A

**Attachments**

N/A

**Comment by maasg** [comment]
We need to define what's an 'experiment' is to provide the context for this feature request.

**Comment by adrien-layer** [comment]
in our current context and from user's usage like [this one](https://github.com/layerai/sdk/issues/314#issuecomment-1216605427)

an experiment is for example a model train `account/project/models/model-foo?v=1.2`|`account/project/models/model-foo:1.2`

so my understanding is:
a label like `production` could be set on a given model train (v1.2) and then these would be equivalent:
- `account/project/models/model-foo?v=1.2`
- `account/project/models/model-foo?label=production`

what I would like to determine though is whether we enable having different experiments with same labels?

is it useful to have for example several experiments labeled with `production-candidate` so we can compare them more easily for example?

or can a label be only on a single experiment (model train)?
