### ISSUE TITLE
[Metadata Store]: Support logging lists and numpy arrays

### ISSUE THREAD

**Issue by volkangurel** [layerai/roadmap#4]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**

I would like to be able to log lists and numpy arrays, like so:

```python
items = ["a","b"]
layer.log({"list":items})
```

```python
import numpy as np
np_items = np.array([1, 2, 3, 4, 5])
layer.log({"np_list":np_items})
```

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**

I'd like to log more types of data in the metadata store.

**Are you currently working around this issue?**

I can log these as strings, but that's not ideal.

**Additional context**
N/A

**Attachments**
N/A

**Comment by cihati** [comment]
List support is added via https://github.com/layerai/sdk/pull/289
